In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset=pd.read_csv("CKD.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0,0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0,2,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3,0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0,0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0,0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
#convert & Drop
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3,0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2,0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1,0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1,0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0,0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0,0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0,2,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3,0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0,0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0,0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [4]:
#Balanced / Inbalanced
dataset['classification_yes'].value_counts()

1    249
0    150
Name: classification_yes, dtype: int64

In [5]:
#View the columns
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [6]:
#Split Input and Output
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset[['classification_yes']]

In [7]:
indep.shape

(399, 27)

In [8]:
dep

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [9]:
#split into training set and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [10]:
#Standaisation
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [11]:
#Model Creation Grid
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
param_grid={'criterion':['gini','entropy','log_loss'],
           'max_features':['auto','sqrt','log2'],
           'class_weight':['balanced','blanced_subsample'],
           'n_estimators':[10,50,100]}
grid=GridSearchCV(RandomForestClassifier(), param_grid, refit=True, verbose=3, n_jobs=-1, scoring='f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 54 candidates, totalling 270 fits

C:\Users\new\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning:
180 fits failed out of a total of 270.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
45 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\new\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 681, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\new\Anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 458, in fit
    for i, t in enumerate(trees)
  File "C:\Users\new\Anaconda3\lib\site-packages\joblib\parallel.py", line 921, in __call__
    if self.dispatch_one_batch(iterator):
  File "C:\Users\new\Anaconda3\lib\site-packages\joblib\parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\new\Anaconda3\lib\site-packages\joblib\parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\new\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "C:\Users\new\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "C:\Users\new\Anaconda3\lib\site-packages\joblib\parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "C:\Users\new\Anaconda3\lib\site-packages\joblib\parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "C:\Users\new\Anaconda3\lib\site-packages\sklearn\utils\fixes.py", line 209, in __call__
    return self.function(*args, **kwargs)
  File "C:\Users\new\Anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 184, in _parallel_build_trees
    tree.fit(X, y, sample_weight=curr_sample_weight, check_input=False)
  File "C:\Users\new\Anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 942, in fit
    X_idx_sorted=X_idx_sorted,
  File "C:\Users\new\Anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 352, in fit
    criterion = CRITERIA_CLF[self.criterion](
KeyError: 'log_loss'

--------------------------------------------------------------------------------
135 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\new\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 681, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\new\Anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 366, in fit
    y, expanded_class_weight = self._validate_y_class_weight(y)
  File "C:\Users\new\Anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 751, in _validate_y_class_weight
    % self.class_weight
ValueError: Valid presets for class_weight include "balanced" and "balanced_subsample".Given "blanced_subsample".

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\new\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:972: UserWarning: One or more of the test scores are non-finite: [0.96445716 0.97516981 0.96769955 0.96795968 0.98218175 0.97486536
 0.97137236 0.98207914 0.97841839 0.96781568 0.97476403 0.97503791
 0.98211447 0.97153742 0.97486536 0.96090459 0.98194817 0.97839515
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan]
  category=UserWarning,
C:\Users\new\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:926: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'class_weight': ['balanced', 'blanced_subsample'],
                         'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 50, 100]},
             scoring='f1_weighted', verbose=3)

In [12]:
#save the model
re=grid.cv_results_

In [13]:
#confusion_matrix
grid_predictions=grid.predict(x_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)

In [14]:
#classification report
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_predictions)

In [15]:
#f1 score
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test, grid_predictions, average='weighted')
print("The f1_macro value for best parameter{}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter{'class_weight': 'balanced', 'criterion': 'gini', 'max_features': 'sqrt', 'n_estimators': 50}: 1.0

In [16]:
#view the confusion_matrix
print("The Confusion Matrix:\n",cm)

The Confusion Matrix:
 [[45  0]
 [ 0 75]]

In [17]:
#view the classification report
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        45
           1       1.00      1.00      1.00        75

    accuracy                           1.00       120
   macro avg       1.00      1.00      1.00       120
weighted avg       1.00      1.00      1.00       120

In [18]:
#roc_auc_score probability
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

1.0

In [19]:
#create the table
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_class_weight,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.053132,0.003789,0.009419,0.002141,balanced,gini,auto,10,"{'class_weight': 'balanced', 'criterion': 'gin...",0.982221,0.963889,0.929513,0.946663,1.000000,0.964457,0.024968,17
1,0.180846,0.006525,0.015407,0.005290,balanced,gini,auto,50,"{'class_weight': 'balanced', 'criterion': 'gin...",1.000000,0.982051,0.929513,0.964286,1.000000,0.975170,0.026395,7
2,0.320329,0.011025,0.039609,0.006112,balanced,gini,auto,100,"{'class_weight': 'balanced', 'criterion': 'gin...",1.000000,0.945469,0.947015,0.964286,0.981728,0.967700,0.020851,16
3,0.041158,0.006312,0.009444,0.007956,balanced,gini,sqrt,10,"{'class_weight': 'balanced', 'criterion': 'gin...",0.982221,0.982051,0.929513,0.964286,0.981728,0.967960,0.020412,14
4,0.163704,0.008944,0.019974,0.007421,balanced,gini,sqrt,50,"{'class_weight': 'balanced', 'criterion': 'gin...",1.000000,0.982051,0.964572,0.964286,1.000000,0.982182,0.015908,1
5,0.306287,0.012335,0.037569,0.002708,balanced,gini,sqrt,100,"{'class_weight': 'balanced', 'criterion': 'gin...",1.000000,0.945469,0.964572,0.964286,1.000000,0.974865,0.021659,9
6,0.041190,0.003821,0.006670,0.008195,balanced,gini,log2,10,"{'class_weight': 'balanced', 'criterion': 'gin...",0.982221,0.963889,0.964572,0.964286,0.981894,0.971372,0.008728,13
7,0.163487,0.012903,0.023864,0.005115,balanced,gini,log2,50,"{'class_weight': 'balanced', 'criterion': 'gin...",1.000000,0.963889,0.982221,0.964286,1.000000,0.982079,0.016061,3
8,0.336390,0.008636,0.039587,0.002330,balanced,gini,log2,100,"{'class_weight': 'balanced', 'criterion': 'gin...",1.000000,0.945469,0.964572,0.982051,1.000000,0.978418,0.021081,5
9,0.044523,0.007270,0.006632,0.005258,balanced,entropy,auto,10,"{'class_weight': 'balanced', 'criterion': 'ent...",1.000000,0.927778,0.947015,0.964286,1.000000,0.967816,0.028705,15
10,0.191515,0.011744,0.025148,0.008471,balanced,entropy,auto,50,"{'class_weight': 'balanced', 'criterion': 'ent...",1.000000,0.945469,0.964572,0.982051,0.981728,0.974764,0.018442,11
11,0.341359,0.007655,0.033868,0.003448,balanced,entropy,auto,100,"{'class_weight': 'balanced', 'criterion': 'ent...",1.000000,0.963889,0.947015,0.964286,1.000000,0.975038,0.021314,8
12,0.048086,0.005690,0.003322,0.004073,balanced,entropy,sqrt,10,"{'class_weight': 'balanced', 'criterion': 'ent...",0.982221,1.000000,0.964572,0.982051,0.981728,0.982114,0.011205,2
13,0.179223,0.006632,0.021179,0.006772,balanced,entropy,sqrt,50,"{'class_weight': 'balanced', 'criterion': 'ent...",1.000000,0.963889,0.929513,0.964286,1.000000,0.971537,0.026448,12
14,0.330324,0.015469,0.037418,0.008094,balanced,entropy,sqrt,100,"{'class_weight': 'balanced', 'criterion': 'ent...",1.000000,0.945469,0.964572,0.964286,1.000000,0.974865,0.021659,9
15,0.044104,0.005829,0.009018,0.007950,balanced,entropy,log2,10,"{'class_weight': 'balanced', 'criterion': 'ent...",0.964572,0.946153,0.929513,0.964286,1.000000,0.960905,0.023479,18
16,0.180959,0.022859,0.023827,0.004779,balanced,entropy,log2,50,"{'class_weight': 'balanced', 'criterion': 'ent...",1.000000,0.945469,0.982221,0.982051,1.000000,0.981948,0.019913,4
17,0.339069,0.009233,0.035507,0.002494,balanced,entropy,log2,100,"{'class_weight': 'balanced', 'criterion': 'ent...",1.000000,0.945469,0.982221,0.964286,1.000000,0.978395,0.021125,6
18,0.025971,0.012968,0.000000,0.000000,balanced,log_loss,auto,10,"{'class_weight': 'balanced', 'criterion': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,38
19,0.090512,0.008312,0.000000,0.000000,balanced,log_loss,auto,50,"{'class_weight': 'balanced', 'criterion': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,39
20,0.164206,0.013215,0.000000,0.000000,balanced,log_loss,auto,100,"{'class_weight': 'balanced', 'criterion': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,40
21,0.030221,0.006524,0.000000,0.000000,balanced,log_loss,sqrt,10,"{'class_weight': 'balanced', 'criterion': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,41
22,0.090117,0.004317,0.000000,0.000000,balanced,log_loss,sqrt,50,"{'class_weight': 'balanced', 'criterion': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,42
23,0.164775,0.006464,0.000000,0.000000,balanced,log_loss,sqrt,100,"{'class_weight': 'balanced', 'criterion': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,43
24,0.032057,0.010558,0.000000,0.000000,balanced,log_loss,log2,10,"{'class_weight': 'balanced', 'criterion': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,44
25,0.091064,0.008312,0.000000,0.000000,balanced,log_loss,log2,50,"{'class_weight': 'balanced', 'criterion': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,45
26,0.141435,0.006057,0.000000,0.000000,balanced,log_loss,log2,100,"{'class_weight': 'balanced', 'criterion': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,36
27,0.012496,0.005714,0.000000,0.000000,blanced_subsample,gini,auto,10,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,47
28,0.015635,0.011605,0.000000,0.000000,blanced_subsample,gini,auto,50,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,48
29,0.009922,0.006284,0.000000,0.000000,blanced_subsample,gini,auto,100,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,49
30,0.006248,0.007653,0.000000,0.000000,blanced_subsample,gini,sqrt,10,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,50
31,0.012499,0.006250,0.000000,0.000000,blanced_subsample,gini,sqrt,50,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,51
32,0.003129,0.006257,0.000000,0.000000,blanced_subsample,gini,sqrt,100,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,52
33,0.010339,0.008442,0.000000,0.000000,blanced_subsample,gini,log2,10,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,37
34,0.009651,0.007894,0.000000,0.000000,blanced_subsample,gini,log2,50,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,53
35,0.013666,0.007136,0.000000,0.000000,blanced_subsample,gini,log2,100,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,35
36,0.007504,0.009133,0.000000,0.000000,blanced_subsample,entropy,auto,10,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,19
37,0.009378,0.007657,0.000000,0.000000,blanced_subsample,entropy,auto,50,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
38,0.013494,0.005295,0.000000,0.000000,blanced_subsample,entropy,auto,100,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
39,0.014209,0.006033,0.000000,0.000000,blanced_subsample,entropy,sqrt,10,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,22
40,0.014209,0.006033,0.000000,0.000000,blanced_subsample,entropy,sqrt,50,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,23
41,0.014293,0.007391,0.000000,0.000000,blanced_subsample,entropy,sqrt,100,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,24
42,0.017139,0.002077,0.000000,0.000000,blanced_subsample,entropy,log2,10,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
43,0.015827,0.000385,0.000000,0.000000,blanced_subsample,entropy,log2,50,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
44,0.012505,0.006252,0.000000,0.000000,blanced_subsample,entropy,log2,100,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,27
45,0.012884,0.006207,0.000000,0.000000,blanced_subsample,log_loss,auto,10,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,34
46,0.019631,0.006039,0.000000,0.000000,blanced_subsample,log_loss,auto,50,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,28
47,0.006910,0.008023,0.000000,0.000000,blanced_subsample,log_loss,auto,100,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,29
48,0.012945,0.011834,0.000000,0.000000,blanced_subsample,log_loss,sqrt,10,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,30
49,0.009561,0.012634,0.000000,0.000000,blanced_subsample,log_loss,sqrt,50,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
50,0.009620,0.012527,0.000000,0.000000,blanced_subsample,log_loss,sqrt,100,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,32
51,0.015812,0.010167,0.000000,0.000000,blanced_subsample,log_loss,log2,10,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,33
52,0.006432,0.007882,0.000000,0.000000,blanced_subsample,log_loss,log2,50,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,46
53,0.015868,0.000333,0.000000,0.000000,blanced_subsample,log_loss,log2,100,"{'class_weight': 'blanced_subsample', 'criteri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,54

In [20]:
import pickle
filename="Finalized_Model_RF.sav"
pickle.dump(grid,open(filename,'wb'))

In [22]:
age=float(input("Age:"))
bp=float(input("BP:"))
al=float(input("AL:"))
su=float(input("SU:"))
bgr=float(input("BGR:"))
bu=float(input("BU:"))
sc=float(input("SC:"))
sod=float(input("SOD:"))
pot=float(input("POT:"))
hrmo=float(input("HRMO:"))
pcv=float(input("PCV:"))
wc=float(input("WC:"))
rc=float(input("RC:"))
sg_b=int(input("SG_B:"))
sg_c=int(input("SG_C:")) 
sg_d=int(input("SG_D:"))
sg_e=int(input("SG_E:"))
rbc=int(input("RBC 0 or 1:"))
pc=int(input("PC 0 or 1:"))
pcc=int(input("PCC 0 or 1:"))
ba=int(input("BA 0 or 1:"))
htn=int(input("HTN 0 or 1:"))
dm=int(input("DM 0 or 1:"))
cad=int(input("CAD 0 or 1:")) 
appet=int(input("APPET 0 or 1:"))
pe=int(input("PE 0 or 1:"))
ane=int(input("ANE 0 or 1:"))

Age:51.49230769
BP:80
AL:0
SU:0
BGR:100
BU:49
SC:1
SOD:140
POT:5
HRMO:16.3
PCV:53
WC:8500
RC:4.9
SG_B:0
SG_C:0
SG_D:0
SG_E:0
RBC 0 or 1:1
PC 0 or 1:1
PCC 0 or 1:0
BA 0 or 1:0
HTN 0 or 1:0
DM 0 or 1:0
CAD 0 or 1:0
APPET 0 or 1:1
PE 0 or 1:0
ANE 0 or 1:0

In [23]:
Future_Prediction=grid.predict([[age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,pcv,wc,rc,sg_b,sg_c,sg_d,sg_e,
                                 rbc,pc,pcc,ba,htn,dm,cad,appet,pe,ane]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]