In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset=pd.read_csv("CKD.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0,0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0,2,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3,0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0,0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0,0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
#convert & Drop
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3,0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2,0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1,0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1,0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0,0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0,0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0,2,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3,0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0,0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0,0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [4]:
#Balanced / Inbalanced
dataset['classification_yes'].value_counts()

1    249
0    150
Name: classification_yes, dtype: int64

In [5]:
#View the columns
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [6]:
#Split Input and Output
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset[['classification_yes']]

In [7]:
indep.shape

(399, 27)

In [8]:
dep

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [9]:
#split into training set and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [10]:
#Standaisation
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
x_train

array([[-0.67992978,  0.26534721,  0.13647691, ...,  0.50671171,
        -0.51229234, -0.43852901],
       [ 0.30730707,  0.26534721, -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901],
       [ 0.43071168,  1.80469462,  2.56692738, ...,  0.50671171,
        -0.51229234,  2.28035085],
       ...,
       [-0.43312057,  0.26534721, -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901],
       [-1.35865512,  0.26534721, -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901],
       [-0.06290675, -1.2740002 , -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901]])

In [11]:
#Model Creation Grid
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
param_grid={'criterion':['gini','entropy'],
           'max_features':['auto','sqrt','log2'],
           'class_weight':['balanced','balanced_subsample'],
           'n_estimators':[10,50,100]}
grid=GridSearchCV(RandomForestClassifier(), param_grid, refit=True, verbose=3, n_jobs=-1, scoring='f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits

C:\Users\new\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:926: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'class_weight': ['balanced', 'balanced_subsample'],
                         'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 50, 100]},
             scoring='f1_weighted', verbose=3)

In [12]:
#save the model
re=grid.cv_results_

In [13]:
#confusion_matrix
grid_predictions=grid.predict(x_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)

In [14]:
#classification report
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_predictions)

In [15]:
#f1 score
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test, grid_predictions, average='weighted')
print("The f1_macro value for best parameter{}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter{'class_weight': 'balanced_subsample', 'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 100}: 0.9916844900066377

In [16]:
#view the confusion_matrix
print("The Confusion Matrix:\n",cm)

The Confusion Matrix:
 [[45  0]
 [ 1 74]]

In [17]:
#view the classification report
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        45
           1       1.00      0.99      0.99        75

    accuracy                           0.99       120
   macro avg       0.99      0.99      0.99       120
weighted avg       0.99      0.99      0.99       120

In [18]:
#roc_auc_score probability
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

0.9997037037037038

In [19]:
#create the table
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_class_weight,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.033313,0.006030,0.003499,0.002907,balanced,gini,auto,10,"{'class_weight': 'balanced', 'criterion': 'gin...",0.982221,0.945469,0.964572,0.964286,1.000000,0.971310,0.018464,25
1,0.096072,0.002074,0.011685,0.007616,balanced,gini,auto,50,"{'class_weight': 'balanced', 'criterion': 'gin...",0.982221,0.963889,0.964572,0.964286,1.000000,0.974994,0.014312,16
2,0.178390,0.008027,0.014805,0.004909,balanced,gini,auto,100,"{'class_weight': 'balanced', 'criterion': 'gin...",1.000000,0.945469,0.947015,0.982051,1.000000,0.974907,0.024310,17
3,0.027376,0.007185,0.001409,0.001564,balanced,gini,sqrt,10,"{'class_weight': 'balanced', 'criterion': 'gin...",1.000000,0.982221,0.964572,0.964286,0.981728,0.978561,0.013286,6
4,0.098322,0.003433,0.005121,0.003616,balanced,gini,sqrt,50,"{'class_weight': 'balanced', 'criterion': 'gin...",1.000000,0.927778,0.964572,0.964286,1.000000,0.971327,0.026967,24
5,0.179063,0.008786,0.024137,0.004832,balanced,gini,sqrt,100,"{'class_weight': 'balanced', 'criterion': 'gin...",1.000000,0.945469,0.947015,0.964286,1.000000,0.971354,0.024305,19
6,0.024478,0.006467,0.001151,0.002302,balanced,gini,log2,10,"{'class_weight': 'balanced', 'criterion': 'gin...",1.000000,0.945469,0.982221,0.964286,1.000000,0.978395,0.021125,12
7,0.089285,0.005952,0.015399,0.004489,balanced,gini,log2,50,"{'class_weight': 'balanced', 'criterion': 'gin...",1.000000,0.945469,0.982221,0.964286,1.000000,0.978395,0.021125,12
8,0.162756,0.003885,0.028352,0.006776,balanced,gini,log2,100,"{'class_weight': 'balanced', 'criterion': 'gin...",1.000000,0.963889,0.964572,0.964286,1.000000,0.978549,0.017516,7
9,0.020197,0.003187,0.007106,0.006183,balanced,entropy,auto,10,"{'class_weight': 'balanced', 'criterion': 'ent...",0.964572,0.963889,0.929513,0.982051,1.000000,0.968005,0.023372,31
10,0.094877,0.003993,0.009788,0.002622,balanced,entropy,auto,50,"{'class_weight': 'balanced', 'criterion': 'ent...",1.000000,0.945469,0.947015,0.964286,0.981728,0.967700,0.020851,35
11,0.182686,0.013999,0.025275,0.006991,balanced,entropy,auto,100,"{'class_weight': 'balanced', 'criterion': 'ent...",1.000000,0.945469,0.947015,0.964286,1.000000,0.971354,0.024305,19
12,0.026150,0.005863,0.001599,0.001958,balanced,entropy,sqrt,10,"{'class_weight': 'balanced', 'criterion': 'ent...",0.982051,0.982051,0.947015,0.927778,1.000000,0.967779,0.026370,34
13,0.102823,0.006455,0.012436,0.006367,balanced,entropy,sqrt,50,"{'class_weight': 'balanced', 'criterion': 'ent...",1.000000,0.945469,0.929513,0.964286,1.000000,0.967853,0.028463,32
14,0.177838,0.001532,0.017378,0.006158,balanced,entropy,sqrt,100,"{'class_weight': 'balanced', 'criterion': 'ent...",1.000000,0.963889,0.947015,0.964286,1.000000,0.975038,0.021314,14
15,0.020504,0.006747,0.000000,0.000000,balanced,entropy,log2,10,"{'class_weight': 'balanced', 'criterion': 'ent...",1.000000,0.963889,0.964572,0.963889,1.000000,0.978470,0.017581,11
16,0.085924,0.005628,0.013665,0.002426,balanced,entropy,log2,50,"{'class_weight': 'balanced', 'criterion': 'ent...",1.000000,0.945469,0.929513,0.982051,1.000000,0.971406,0.028901,18
17,0.175381,0.009909,0.019579,0.003759,balanced,entropy,log2,100,"{'class_weight': 'balanced', 'criterion': 'ent...",1.000000,0.963889,0.964572,0.964286,1.000000,0.978549,0.017516,7
18,0.028459,0.007815,0.002005,0.004010,balanced_subsample,gini,auto,10,"{'class_weight': 'balanced_subsample', 'criter...",0.982051,0.963889,0.982221,0.964286,1.000000,0.978489,0.013448,10
19,0.116222,0.007937,0.011714,0.005313,balanced_subsample,gini,auto,50,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.982051,0.947015,0.982051,0.981728,0.978569,0.017258,5
20,0.233658,0.001826,0.017471,0.003908,balanced_subsample,gini,auto,100,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.945469,0.947015,0.964286,1.000000,0.971354,0.024305,19
21,0.033108,0.004921,0.001605,0.003209,balanced_subsample,gini,sqrt,10,"{'class_weight': 'balanced_subsample', 'criter...",0.982221,0.945469,0.964572,0.964286,1.000000,0.971310,0.018464,25
22,0.118984,0.004203,0.012508,0.006254,balanced_subsample,gini,sqrt,50,"{'class_weight': 'balanced_subsample', 'criter...",0.982221,0.945469,0.964572,0.964286,0.981728,0.967655,0.013589,36
23,0.240100,0.008480,0.020411,0.006092,balanced_subsample,gini,sqrt,100,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.963889,0.947015,0.964286,1.000000,0.975038,0.021314,14
24,0.030690,0.008306,0.003434,0.006868,balanced_subsample,gini,log2,10,"{'class_weight': 'balanced_subsample', 'criter...",0.982221,0.945469,0.964572,0.964286,1.000000,0.971310,0.018464,25
25,0.114834,0.007538,0.016829,0.001504,balanced_subsample,gini,log2,50,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.982051,0.947015,0.964286,1.000000,0.978670,0.020641,3
26,0.233520,0.004426,0.020964,0.007581,balanced_subsample,gini,log2,100,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.963889,0.964572,0.982051,1.000000,0.982102,0.015998,2
27,0.031217,0.006909,0.004291,0.006100,balanced_subsample,entropy,auto,10,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.927778,0.947015,0.964286,1.000000,0.967816,0.028705,33
28,0.119278,0.004208,0.010146,0.008515,balanced_subsample,entropy,auto,50,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.945469,0.947015,0.964286,1.000000,0.971354,0.024305,19
29,0.234874,0.016754,0.017297,0.003328,balanced_subsample,entropy,auto,100,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.945469,0.947015,0.982051,0.981728,0.971253,0.021471,28
30,0.024487,0.007205,0.009696,0.007715,balanced_subsample,entropy,sqrt,10,"{'class_weight': 'balanced_subsample', 'criter...",0.982221,0.963889,0.912029,0.982051,1.000000,0.968038,0.030243,30
31,0.119037,0.002963,0.001667,0.003335,balanced_subsample,entropy,sqrt,50,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.982051,0.947015,0.964286,1.000000,0.978670,0.020641,3
32,0.186656,0.056475,0.012514,0.011707,balanced_subsample,entropy,sqrt,100,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.945469,0.947015,0.982051,0.981728,0.971253,0.021471,28
33,0.031336,0.001260,0.000000,0.000000,balanced_subsample,entropy,log2,10,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.946153,0.982221,0.964286,1.000000,0.978532,0.020913,9
34,0.103008,0.023580,0.004741,0.009483,balanced_subsample,entropy,log2,50,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.945469,0.947015,0.964286,1.000000,0.971354,0.024305,19
35,0.130294,0.036917,0.009380,0.007659,balanced_subsample,entropy,log2,100,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.982051,0.947015,0.982051,1.000000,0.982223,0.019348,1

In [21]:
age=int(input("Age:"))
bp=int(input("BP:"))
al=int(input("AL:"))
su=int(input("SU:"))
bgr=int(input("BGR:"))
bu=int(input("BU:"))
sc=int(input("SC:"))
sod=int(input("SOD:"))
pot=int(input("POT:"))
hrmo=int(input("HRMO:"))
pcv=int(input("PCV:"))
wc=int(input("WC:"))
rc=int(input("RC:"))
sg_b=int(input("SG_B:"))
sg_c=int(input("SG_C:")) 
sg_d=int(input("SG_D:"))
sg_e=int(input("SG_E:"))
rbc=int(input("RBC 0 or 1:"))
pc=int(input("PC 0 or 1:"))
pcc=int(input("PCC 0 or 1:"))
ba=int(input("BA 0 or 1:"))
htn=int(input("HTN 0 or 1:"))
dm=int(input("DM 0 or 1:"))
cad=int(input("CAD 0 or 1:")) 
appet=int(input("APPET 0 or 1:"))
pe=int(input("PE 0 or 1:"))
ane=int(input("ANE 0 or 1:"))

Age:51
BP:80
AL:0
SU:0
BGR:100
BU:49
SC:1
SOD:140
POT:5
HRMO:16
PCV:53
WC:8500
RC:5
SG_B:0
SG_C:0
SG_D:0
SG_E:0
RBC 0 or 1:1
PC 0 or 1:1
PCC 0 or 1:0
BA 0 or 1:0
HTN 0 or 1:0
DM 0 or 1:0
CAD 0 or 1:0
APPET 0 or 1:1
PE 0 or 1:0
ANE 0 or 1:0

In [22]:
input_data=np.array([[age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,pcv,wc,rc,sg_b,sg_c,sg_d,sg_e,
                      rbc,pc,pcc,ba,htn,dm,cad,appet,pe,ane]])
input_data_scaled=sc.transform(input_data)

AttributeError: 'int' object has no attribute 'transform'

In [ ]:
Future_Prediction=grid.predict(input_data_scaled)
print("Future_Prediction={}".format(Future_Prediction))

In [ ]:
import pickle
filename="Finalized_Model_RF.sav"
pickle.dump(grid,open(filename,'wb'))