In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset=pd.read_csv("CKD.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0,0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0,2,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3,0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0,0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0,0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
#convert & Drop
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3,0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2,0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1,0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1,0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0,0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0,0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0,2,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3,0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0,0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0,0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [4]:
#Balanced / Inbalanced
dataset['classification_yes'].value_counts()

1    249
0    150
Name: classification_yes, dtype: int64

In [5]:
#View the columns
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [6]:
#Split Input and Output
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset[['classification_yes']]

In [7]:
indep.shape

(399, 27)

In [8]:
dep

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [9]:
#split into training set and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [10]:
#Standaisation
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
x_train

array([[-0.67992978,  0.26534721,  0.13647691, ...,  0.50671171,
        -0.51229234, -0.43852901],
       [ 0.30730707,  0.26534721, -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901],
       [ 0.43071168,  1.80469462,  2.56692738, ...,  0.50671171,
        -0.51229234,  2.28035085],
       ...,
       [-0.43312057,  0.26534721, -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901],
       [-1.35865512,  0.26534721, -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901],
       [-0.06290675, -1.2740002 , -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901]])

In [11]:
#Model Creation Grid
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
param_grid={'criterion':['gini','entropy'],
           'max_features':['auto','sqrt','log2'],
           'class_weight':['balanced','balanced_subsample'],
           'n_estimators':[10,50,100]}
grid=GridSearchCV(RandomForestClassifier(), param_grid, refit=True, verbose=3, n_jobs=-1, scoring='f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits

C:\Users\new\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:926: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'class_weight': ['balanced', 'balanced_subsample'],
                         'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 50, 100]},
             scoring='f1_weighted', verbose=3)

In [12]:
#save the model
re=grid.cv_results_

In [13]:
#confusion_matrix
grid_predictions=grid.predict(x_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)

In [14]:
#classification report
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_predictions)

In [15]:
#f1 score
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test, grid_predictions, average='weighted')
print("The f1_macro value for best parameter{}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter{'class_weight': 'balanced_subsample', 'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 100}: 1.0

In [16]:
#view the confusion_matrix
print("The Confusion Matrix:\n",cm)

The Confusion Matrix:
 [[45  0]
 [ 0 75]]

In [17]:
#view the classification report
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        45
           1       1.00      1.00      1.00        75

    accuracy                           1.00       120
   macro avg       1.00      1.00      1.00       120
weighted avg       1.00      1.00      1.00       120

In [18]:
#roc_auc_score probability
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

1.0

In [19]:
#create the table
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_class_weight,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.030702,0.007718,0.000000,0.000000,balanced,gini,auto,10,"{'class_weight': 'balanced', 'criterion': 'gin...",0.964572,0.982051,0.964572,0.964286,0.981728,0.971442,0.008532,24
1,0.084384,0.007657,0.006252,0.007657,balanced,gini,auto,50,"{'class_weight': 'balanced', 'criterion': 'gin...",1.000000,0.982051,0.964572,0.964286,1.000000,0.982182,0.015908,5
2,0.158610,0.009199,0.017232,0.003208,balanced,gini,auto,100,"{'class_weight': 'balanced', 'criterion': 'gin...",1.000000,0.945469,0.947015,0.964286,1.000000,0.971354,0.024305,27
3,0.020615,0.009338,0.000000,0.000000,balanced,gini,sqrt,10,"{'class_weight': 'balanced', 'criterion': 'gin...",0.982221,0.946153,0.894531,0.946153,1.000000,0.953811,0.036255,36
4,0.081347,0.007936,0.006250,0.007655,balanced,gini,sqrt,50,"{'class_weight': 'balanced', 'criterion': 'gin...",1.000000,0.963889,0.947015,0.982051,1.000000,0.978591,0.020697,8
5,0.153142,0.006252,0.015626,0.000005,balanced,gini,sqrt,100,"{'class_weight': 'balanced', 'criterion': 'gin...",1.000000,0.982051,0.964572,0.964286,1.000000,0.982182,0.015908,5
6,0.018752,0.006251,0.006251,0.007655,balanced,gini,log2,10,"{'class_weight': 'balanced', 'criterion': 'gin...",0.982221,0.963889,0.946663,0.964286,1.000000,0.971412,0.018188,25
7,0.081391,0.006192,0.009374,0.007654,balanced,gini,log2,50,"{'class_weight': 'balanced', 'criterion': 'gin...",1.000000,0.982051,0.964572,0.964286,1.000000,0.982182,0.015908,5
8,0.152674,0.009980,0.013378,0.008373,balanced,gini,log2,100,"{'class_weight': 'balanced', 'criterion': 'gin...",1.000000,0.945469,0.964572,0.964286,1.000000,0.974865,0.021659,17
9,0.018756,0.006249,0.006379,0.007816,balanced,entropy,auto,10,"{'class_weight': 'balanced', 'criterion': 'ent...",0.947015,0.982051,0.912029,0.982051,0.963247,0.957279,0.026137,35
10,0.081017,0.006170,0.012502,0.006251,balanced,entropy,auto,50,"{'class_weight': 'balanced', 'criterion': 'ent...",1.000000,0.963889,0.929513,0.964286,1.000000,0.971537,0.026448,22
11,0.164255,0.006997,0.015625,0.000004,balanced,entropy,auto,100,"{'class_weight': 'balanced', 'criterion': 'ent...",1.000000,0.963889,0.947015,0.982051,0.981728,0.974937,0.018037,12
12,0.018752,0.006250,0.006251,0.007655,balanced,entropy,sqrt,10,"{'class_weight': 'balanced', 'criterion': 'ent...",0.982221,0.946153,0.929513,0.964286,0.981728,0.960780,0.020506,34
13,0.084727,0.005953,0.015627,0.000005,balanced,entropy,sqrt,50,"{'class_weight': 'balanced', 'criterion': 'ent...",1.000000,0.982051,0.947015,0.982051,1.000000,0.982223,0.019348,3
14,0.164732,0.008749,0.015763,0.000274,balanced,entropy,sqrt,100,"{'class_weight': 'balanced', 'criterion': 'ent...",1.000000,0.963889,0.947015,0.964286,1.000000,0.975038,0.021314,11
15,0.017363,0.003467,0.012501,0.006251,balanced,entropy,log2,10,"{'class_weight': 'balanced', 'criterion': 'ent...",1.000000,0.945469,0.964572,0.982051,1.000000,0.978418,0.021081,9
16,0.084522,0.007829,0.000000,0.000000,balanced,entropy,log2,50,"{'class_weight': 'balanced', 'criterion': 'ent...",1.000000,0.982051,0.947015,0.982051,1.000000,0.982223,0.019348,3
17,0.153496,0.006442,0.015763,0.000274,balanced,entropy,log2,100,"{'class_weight': 'balanced', 'criterion': 'ent...",1.000000,0.945469,0.964572,0.982051,1.000000,0.978418,0.021081,9
18,0.028128,0.006251,0.003125,0.006251,balanced_subsample,gini,auto,10,"{'class_weight': 'balanced_subsample', 'criter...",0.982221,0.945469,0.929513,0.964286,1.000000,0.964298,0.025141,32
19,0.103414,0.007606,0.012501,0.006250,balanced_subsample,gini,auto,50,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.945469,0.929513,0.982051,1.000000,0.971406,0.028901,26
20,0.207041,0.012062,0.015628,0.000005,balanced_subsample,gini,auto,100,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.963889,0.964572,0.964286,0.981728,0.974895,0.014263,15
21,0.031255,0.000005,0.003125,0.006250,balanced_subsample,gini,sqrt,10,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.946153,0.982221,0.910254,0.981728,0.964071,0.032092,33
22,0.106689,0.012101,0.012502,0.006251,balanced_subsample,gini,sqrt,50,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.945469,0.964572,0.964286,1.000000,0.974865,0.021659,17
23,0.194387,0.008008,0.021881,0.007657,balanced_subsample,gini,sqrt,100,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.945469,0.947015,0.982051,1.000000,0.974907,0.024310,13
24,0.021877,0.007655,0.000000,0.000000,balanced_subsample,gini,log2,10,"{'class_weight': 'balanced_subsample', 'criter...",0.982221,0.963889,0.929513,0.982051,1.000000,0.971535,0.023914,23
25,0.106891,0.006578,0.009378,0.007657,balanced_subsample,gini,log2,50,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.945469,0.964572,0.964286,1.000000,0.974865,0.021659,17
26,0.194306,0.007646,0.012501,0.006250,balanced_subsample,gini,log2,100,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.982051,0.964572,0.982051,1.000000,0.985735,0.013281,1
27,0.025004,0.012502,0.003327,0.006163,balanced_subsample,entropy,auto,10,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.946153,0.947015,0.946663,1.000000,0.967966,0.026157,30
28,0.097089,0.006163,0.012628,0.006319,balanced_subsample,entropy,auto,50,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.945469,0.947015,0.964286,1.000000,0.971354,0.024305,27
29,0.178275,0.027290,0.011451,0.006075,balanced_subsample,entropy,auto,100,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.945469,0.964572,0.964286,1.000000,0.974865,0.021659,17
30,0.031383,0.000259,0.000000,0.000000,balanced_subsample,entropy,sqrt,10,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.927778,0.964572,0.982051,1.000000,0.974880,0.026975,16
31,0.099220,0.006692,0.009376,0.007656,balanced_subsample,entropy,sqrt,50,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.945469,0.947015,0.982051,1.000000,0.974907,0.024310,13
32,0.158472,0.036871,0.015626,0.000004,balanced_subsample,entropy,sqrt,100,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.945469,0.947015,0.964286,1.000000,0.971354,0.024305,27
33,0.025131,0.007500,0.005202,0.006585,balanced_subsample,entropy,log2,10,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.945469,0.912029,0.982051,1.000000,0.967910,0.034310,31
34,0.091661,0.008452,0.009377,0.007657,balanced_subsample,entropy,log2,50,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.963889,0.982221,0.982051,1.000000,0.985632,0.013491,2
35,0.161466,0.017428,0.006251,0.007655,balanced_subsample,entropy,log2,100,"{'class_weight': 'balanced_subsample', 'criter...",1.000000,0.945469,0.964572,0.964286,1.000000,0.974865,0.021659,17

In [20]:
age=float(input("Age:"))
bp=float(input("BP:"))
al=float(input("AL:"))
su=float(input("SU:"))
bgr=float(input("BGR:"))
bu=float(input("BU:"))
sc_input=float(input("SC:"))
sod=float(input("SOD:"))
pot=float(input("POT:"))
hrmo=float(input("HRMO:"))
pcv=float(input("PCV:"))
wc=float(input("WC:"))
rc=float(input("RC:"))
sg_b=int(input("SG_B:"))
sg_c=int(input("SG_C:")) 
sg_d=int(input("SG_D:"))
sg_e=int(input("SG_E:"))
rbc=int(input("RBC 0 or 1:"))
pc=int(input("PC 0 or 1:"))
pcc=int(input("PCC 0 or 1:"))
ba=int(input("BA 0 or 1:"))
htn=int(input("HTN 0 or 1:"))
dm=int(input("DM 0 or 1:"))
cad=int(input("CAD 0 or 1:")) 
appet=int(input("APPET 0 or 1:"))
pe=int(input("PE 0 or 1:"))
ane=int(input("ANE 0 or 1:"))

Age:51.49230769
BP:80
AL:0
SU:0
BGR:100
BU:49
SC:1
SOD:140
POT:5
HRMO:16.3
PCV:53
WC:8500
RC:4.9
SG_B:0
SG_C:0
SG_D:0
SG_E:0
RBC 0 or 1:1
PC 0 or 1:1
PCC 0 or 1:0
BA 0 or 1:0
HTN 0 or 1:0
DM 0 or 1:0
CAD 0 or 1:0
APPET 0 or 1:1
PE 0 or 1:0
ANE 0 or 1:0

In [21]:
input_data=np.array([[age,bp,al,su,bgr,bu,sc_input,sod,pot,hrmo,pcv,wc,rc,sg_b,sg_c,sg_d,sg_e,
                      rbc,pc,pcc,ba,htn,dm,cad,appet,pe,ane]])
input_data_scaled=sc.transform(input_data)

C:\Users\new\Anaconda3\lib\site-packages\sklearn\base.py:442: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"

In [22]:
Future_Prediction=grid.predict(input_data_scaled)
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[0]

In [24]:
import pickle
filename="Finalized_Model_MLCRF.sav"
pickle.dump(grid,open(filename,'wb'))

In [25]:
loaded_model=pickle.load(open("Finalized_Model_MLCRF.sav",'rb'))
result=loaded_model.predict([[51.49230769,80,0,0,100,49,1,140,5,16.3,53,8500,4.9,0,0,0,0,1,1,0,0,0,0,0,1,0,0]])
result

array([1], dtype=uint8)

In [ ]:
loaded_model=pickle.load(open("Finalized_Model_MLCRF.sav",'rb'))
result=loaded_model.predict([[2,76.45994832,3,0,148.1126761,57.48210526,3.077356021,137.528754,4.62724359,
                              12.51815562,38.86890244,8408.191126,0,0,1,0,0,1,0,0,0,0,0,0,1,1,0]])
result